site_name: MobSin Game Engine

repo_url: https://github.com/MatthewWid/MobSin
repo_name: "GitHub"
edit_uri: ""

theme: cinder
docs_dir: "doc"
extra_css: [css/css/global.css]

nav:
    - Home: index.md
    - Documentation:
      - Installation: documentation/install.md
      - Concepts: documentation/concepts.md
      - Game Classes: documentation/classes.md
      - In-Built Libraries: documentation/libraries.md
      - Constants: documentation/constants.md
      - Object Systems: documentation/systems.md
    - Getting Started: getting-started/index.md
    - About:
      - Licence: about/licence.md

markdown_extensions:
    - toc:
        permalink: true